version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  tests: false

formatters:
  enable:
    - gci
    - gofumpt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  fix: false

linters:
  default: all
  disable:
   - nonamedreturns
  settings:
    govet:
      enable-all: true
    staticcheck:
      checks: ["all"]
    gomoddirectives:
      replace-local: true
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close
    decorder:
      # declaration order
      # Default: types before constants before variables before functions
      disable-dec-order-check: false
      disable-init-func-first-check: false
      disable-dec-num-check: false
      disable-type-dec-num-check: false
      disable-const-dec-num-check: false
      disable-var-dec-num-check: false
    gosec:
      config:
        global:
          audit: true
    whitespace:
      multi-if: true
