name: lint

on:
  push:
    branches-ignore:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v6
      - name: Install golang
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
      - name: Run linters
        uses: golangci/golangci-lint-action@v9
