name: tests

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v6
      - name: Install golang
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
      - name: Run tests
        run: go test ./... -race -parallel 2 -shuffle on -v
        env:
          CGO_ENABLED: 1
